data: zehavi

data_file: zehavi_data_file_19

sim: smdpl

param: mvir

file_ext: /home/lom31/emcee_fits/october_2020/

output: zehavi_smdpl_mvir_m19_2.h5

ndim: 5

nwalkers: 20

nsteps: 50000

prior_ranges:
     logMmin_r: [10.0,14.0]
     sigma_logM_r: [0.01,2.5]
     alpha_r: [0.85,5.0]
     logM0_r: [10.0,14.0]
     logM1_r: [10.0,14.0]

guess: [11.69, 1.04, 0.96, 11.66, 12.72]